title: ğŸ˜€ğŸ˜ğŸ˜‰ JSì˜ ê°œë°œ ë¸”ë¡œê·¸ ğŸ˜ğŸ˜†ğŸ˜„
description: ë‚˜ë§Œì˜ ê³µê°„
author: Jiseob Kim
github: https://github.com/JiSeobKim
about: ë§¤ë„ëŸ¬ìš´ iOS ë§Œë“¤ì, ë¿Œì…”
disqus_shortname: https-jiseobkim-github-io
google_analytics: UA-121626260-1
avatar_url: /static/img/mainIcon2.png

enableTags: true
tagarray: [Swift]

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "Jiseob812"
    - icon: fa-github
      link: "https://github.com/JiSeobKim"

share:
  twitter_username: github.io
  fb_appid:

urls:
    - text: Category
      url: /category/Swift
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://jiseobkim.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
